In [55]:
import numpy as np
from numpy.linalg import inv
nodesx=3
nodesy=3
discretization=np.zeros((nodesx,nodesy))
t=1
for i in range(nodesx):
    for j in range(nodesy):
        discretization[i][j]=t
        t+=1
print(discretization)  
Xvelocity=20
Yvelocity=20
Density=25
DeltaX=0.1
DeltaY=0.1
FluxX=0.2
FluxY=0.3
Viscocity=0.3

NorthernTemperature=20
SouthernTemperature=50
EasternTemperature=50
WesternTemperature=20

Fx=Density*Xvelocity
Fy=Density*Yvelocity

Dx=Viscocity/DeltaX
Dy=Viscocity/DeltaY

A=np.zeros((nodesx*nodesy,nodesx*nodesy))
b=np.zeros((nodesx*nodesy,1))
#Top Right corner
for i in range(nodesx):
    for j in range(nodesy):
        if i==0 and j==0:
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]=(-Fy/2)+(Dy*2)+Dy+(Fx/2)+(Dx)+(2*Dx)
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]=(Fx/2)-(Dx) #East
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]=(-1*Fy/2)-(Dy) #South
            b[int(discretization[i][j]-1)][0]=(-1*NorthernTemperature*Fy)-(2*Dy*NorthernTemperature)+(WesternTemperature*Fx)+(2*Dx*WesternTemperature)
        if i==0 and j==nodesx-1:  #Top Right Corner
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]=(-Fy/2)+(+2*Dy)+(Dy)+(-Fx/2)+(2*Dx)+Dx
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]=(-1*Fx/2)-(Dx) #West
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]= (-Fy/2)-(Dy)#South
            b[int(discretization[i][j]-1)][0]=(-Fy*NorthernTemperature)+(2*Dy)-(Fx*EasternTemperature)+(2*Dx)
        if i==nodesy-1 and j==nodesx-1:#Lower right corner
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]=(Fy/2)+(Dy)+(2*Dy)+(-1*Fx/2)+(2*Dx)+(Dx)
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]=(Fy/2)-(Dy) #North
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]= (-Fx/2)-(Dx) #West
            b[int(discretization[i][j]-1)][0]=+(Fy*SouthernTemperature)+(2*Dy*SouthernTemperature)-(Fx*EasternTemperature)+(2*Dx*EasternTemperature)
        if i==nodesy-1 and j==0: #Lower Left Corner
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]=(Fy/2)+(Dy)+(2*Dy)+(Fx/2)+(Dx)+(2*Dx)
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]=(Fy/2)-(Dy) #North
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]=(Fx/2)-(Dx) #East
            b[int(discretization[i][j]-1)][0]=(Fy*SouthernTemperature)+(2*Dy*SouthernTemperature)+(Fx*WesternTemperature)+(2*Dx*WesternTemperature)
for i in range(nodesx):
    for j in range(nodesy):
        if i==0 and j>0 and j<nodesx-1: #Northern Edge
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]= (-1*Fy/2)+(Dy*2)+(Dy)+(Dx)+(Dx)
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]= (-1*Fx/2)+ (-Dx) #West
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]= (Fx/2)+(-Dx) #East
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]= (-1*Fy/2)+(-Dy)#South
            b[int(discretization[i][j]-1)][0]=-Fy*NorthernTemperature+(2*Dy*NorthernTemperature)
            
        if i==nodesy-1 and j>0 and j<nodesx-1:  #Southern Edge
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]= (Dx)+(Dx)+(Fy/2)+(Dy)+(2*Dy)
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]= -(Fx/2)-(Dx) #west
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]= (Fx/2)-Dx #East
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]= (Fy/2)-(Dy) #Norht
            b[int(discretization[i][j]-1)][0]=+(Fy*SouthernTemperature)+(2*Dy*SouthernTemperature)
            
        if i>0 and i<nodesy-1 and j==0:      #Western Edge
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]= +(Dy*2)+(Fx/2)+(Dx)+(2*Dx)
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]= (Fy/2)+(-Dy) #North
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]= (-Fy/2)-(Dy) #South
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]= (Fx/2)-(Dx) #East
            b[int(discretization[i][j]-1)][0]=+Fx*WesternTemperature
            
        if i>0 and i<nodesx-1 and j==nodesx-1: #Eastern Edge
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]= (2*Dy)-(Fx/2)+(2*Dx)+Dx
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]= (Fy/2)-Dy #North
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]= (-Fy/2)-Dy #South
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]= (-Fx/2)-Dx #West
            b[int(discretization[i][j]-1)][0]=-Fx*EasternTemperature       
for i in range(nodesx):
    for j in range(nodesy):           
        if i>0 and i<nodesy-1 and j>0 and j<nodesx-1:
            A[int(discretization[i][j]-1)][int(discretization[i][j]-1)]=(2*Dx)+(2*Dy)
            A[int(discretization[i][j]-1)][int(discretization[i-1][j]-1)]= (Fy/2)-(Dy) #North
            A[int(discretization[i][j]-1)][int(discretization[i+1][j]-1)]= (-Fy/2)+(Dy) #South
            A[int(discretization[i][j]-1)][int(discretization[i][j-1]-1)]= (-Fx/2)-(Dx) #West
            A[int(discretization[i][j]-1)][int(discretization[i][j+1]-1)]= (Fx/2)+(-Dx) #East
            b[int(discretization[i][j]-1)][0]=0
sol=np.dot(inv(A),b)   
print(sol)
np.zeros((nodesx*nodesy,nodesx*nodesy))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[-142.42929541]
 [ 436.97588997]
 [-387.9402742 ]
 [ 416.47951583]
 [-603.146127  ]
 [ 440.39649014]
 [-331.18599859]
 [ 421.47330712]
 [ -85.84368688]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])